language: node_js

sudo: false

node_js:
  - "6"
  - "6.1"
  - "5.11"

before_script:
  - npm install

script:
  - npm run test-all
  - npm run cover:istanbul
  - npm run send-cover-report
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

