name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint & Test
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Doctests
      run: |
        npm install doctest standard --save-dev
        npx doctest **/*.js || true  # TODO: Add all doctests
        npx standard
    
    - name: Unit Tests
      run: |
        npm ci
        npm test
      env:
        CI: true

    - name: Build
      run: |
        npm run build --if-present
